server:
  port: '@server.port@'

management:
  security:
    flag: false
  server:
    port: '@management.port@'
  metrics:
    prometheus:
      enabled: true
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

spring:
  application:
    name: '@project.name@'
    output:
      ansi:
        enabled: always
  redis:
    host: redis-image
    port: 6379
    password:
app:
  timeout-handler: 10
  proxy:
    timeout: 10000
    proxy-line:
      api-key: some-api-key
      url: https://panel.proxyline.net/api/

application:
  redis:
    cache-cron: 0 0 6 * * ?
