server:
  port: '@server.port@'

management:
  security:
    flag: false
  server:
    port: '@management.port@'
  metrics:
    prometheus:
      enabled: true
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

spring:
  application:
    name: '@project.name@'
    output:
      ansi:
        enabled: always
  redis:
    host: marketdb-redis-do-user-9153772-0.b.db.ondigitalocean.com
    port: 25061
    username: default
    password: u7xpmAET83thnhjz
    ssl: true
app:
  timeout-handler: 10
  proxy:
    timeout: 10000
    proxy-line:
      api-key: v3ityelj2eh53re1ukysymrx7ci0oaytsn0ozt33
      url: https://panel.proxyline.net/api/

loki:
  host: localhost
  enabled: false

application:
  scheduler:
    lockAtMost: 15m
    redis:
      cache-cron: 0 0/15 * * * ?
