server:
  port: '@server.port@'

management:
  security:
    flag: false
  server:
    port: '@management.port@'
  metrics:
    prometheus:
      enabled: true
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

spring:
  application:
    name: '@project.name@'
    output:
      ansi:
        enabled: always
  redis:
    host:
    port:
    username:
    password:
    ssl: true
app:
  timeout-handler: 20
  proxy:
    retries:
      attempts: 4
      exponent: 1.5
    timeout: 5000

integration:
  mobile-proxy:
    change-ip-cron: 0/15 * * ? * *
    api-key: eec7092e9738914593b3a102e15b8852
    url: https://mobileproxy.space/api.html
  proxy-line:
    api-key:
    url: https://panel.proxyline.net/api/

loki:
  host: localhost
  enabled: false

application:
  forbidden-expire: 7
  scheduler:
    lockAtMost: 15m
    redis:
      cache-cron: 0 0/5 * * * ?
      forbidden-url-cron: 0 0/1 * * * ?
