server:
  port: '@server.port@'

management:
  security:
    flag: false
  server:
    port: '@management.port@'
  metrics:
    prometheus:
      enabled: true
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

spring:
  application:
    name: '@project.name@'
    output:
      ansi:
        enabled: always
  redis:
    host: 127.0.0.1
    port: 6379
    password:
app:
  proxy:
    api-key: 8e49f60a33-1752c4ba05-86fa429832
    url: https://proxy6.net/api/

application:
  redis:
    cache-cron: 0 0 6 * * ?
