server:
  port: '@server.port@'

management:
  security:
    flag: false
  server:
    port: '@management.port@'
  metrics:
    prometheus:
      enabled: true
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

spring:
  application:
    name: '@project.name@'
    output:
      ansi:
        enabled: always
  redis:
    host:
    port:
    username:
    password:
    ssl: true
app:
  timeout-handler: 20
  proxy:
    retries:
      attempts: 4
      exponent: 1.5
    timeout: 5000
    proxy-line:
      api-key:
      url:

loki:
  host: localhost
  enabled: false

application:
  forbidden-expire: 7
  scheduler:
    lockAtMost: 15m
    redis:
      cache-cron: 0 0/5 * * * ?
      forbidden-url-cron: 0 0/1 * * * ?
