spring:
  codec:
    log-request-details: false
  application:
    name: '@project.name@'
    output:
      ansi:
        enabled: always
  redis:
    host: 0.0.0.0
    port: 55000
    password: redispw
  mvc:
    log-request-details: false
app:
  redis:
    local: true
  timeout-handler: 10
  proxy:
    timeout: 10000

integration:
  proxys-io:
    url: https://proxys.io/ru/api/v2
    api-key:
  proxy-house:
    api-key:
    url: https://proxy.house/api/open/v1/
  proxy-line:
    api-key:
    url: https://panel.proxyline.net/api/

application:
  forbidden-expire: 1
  scheduler:
    lockAtMost: 15m
    redis:
      cache-cron: 0 0/1 * * * ?
      forbidden-url-cron: 0/10 * * * * ?
      update-user-agents: 0 0 3 1/1 * ?

logging:
  level:
    io:
      netty:
        channel:
          DefaultChannelPipeline: DEBUG
    dev:
      crashteam:
        styx:
          service:
            web:
              WebClientService:
              AdvancedConversationService:
    reactor:
      netty:
        http:
          client:

