server:
  port: '@server.port@'

management:
  security:
    flag: false
  server:
    port: '@management.port@'
  metrics:
    prometheus:
      enabled: true
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

spring:
  application:
    name: '@project.name@'
    output:
      ansi:
        enabled: always
  redis:
    host:
    port:
    username:
    password:
    ssl: true
app:
  redis:
    local: false
  timeout-handler: 20
  proxy:
    retries:
      timeout: 1000
      attempts: 4
      exponent: 1.5
    timeout: 5000

integration:
  proxys-io:
    url: https://proxys.io/ru/api/v2
    api-key:
  mobile-proxy:
    api-key:
    url: https://mobileproxy.space/api.html
  proxy-line:
    api-key:
    url: https://panel.proxyline.net/api/
  proxy-house:
    api-key:
    url: https://proxy.house/api/open/v1/

loki:
  host: localhost
  enabled: false

application:
  forbidden-expire: 7
  scheduler:
    mobile-proxy:
      change-ip-cron: 0/15 * * ? * *
      reload-proxy: 0 0/30 * * * ?
    lockAtMost: 15m
    redis:
      cache-cron: 0 0/5 * * * ?
      forbidden-url-cron: 0 0/1 * * * ?
      update-user-agents: 0 0 3 1/1 * ? *
